// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSaloon.Data;

namespace ProjectSaloon.Migrations
{
    [DbContext(typeof(ProjectSaloonContext))]
    [Migration("20210201202039_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectSaloon.Models.Beautician", b =>
                {
                    b.Property<int>("BeauticianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BeauticianName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContactNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int>("SaloonID")
                        .HasColumnType("int");

                    b.HasKey("BeauticianID");

                    b.HasIndex("SaloonID");

                    b.ToTable("Beautician");
                });

            modelBuilder.Entity("ProjectSaloon.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeauticianID")
                        .HasColumnType("int");

                    b.Property<int>("ContactNumber")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Expenses")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.HasIndex("BeauticianID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("ProjectSaloon.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SaloonID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("SaloonID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ProjectSaloon.Models.Saloon", b =>
                {
                    b.Property<int>("SaloonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Contact_Number")
                        .HasColumnType("int");

                    b.Property<string>("SaloonAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaloonName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SaloonID");

                    b.ToTable("Saloon");
                });

            modelBuilder.Entity("ProjectSaloon.Models.Beautician", b =>
                {
                    b.HasOne("ProjectSaloon.Models.Saloon", "Saloon_obj")
                        .WithMany()
                        .HasForeignKey("SaloonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectSaloon.Models.Customer", b =>
                {
                    b.HasOne("ProjectSaloon.Models.Beautician", "Beautician_obj")
                        .WithMany()
                        .HasForeignKey("BeauticianID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectSaloon.Models.Product", b =>
                {
                    b.HasOne("ProjectSaloon.Models.Saloon", "Saloon_obj")
                        .WithMany()
                        .HasForeignKey("SaloonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
